### ISSUE TITLE
updateExistingPivot without id argument?

### ISSUE THREAD

**Issue by hackel** [ankurk91/laravel-eloquent-relationships#1]
Currently `InteractsWithPivotTable::updateExistingPivot` requires an `id` (foreign key) argument to specify which pivot table record to update, as it was written for a BelongsToMany relationship.  When used with BelongsToOne, however, we know there is only one pivot record per parent, so the `id` argument can be eliminated.

~~My question is, if we were to add it to this package, is it appropriate to change the method signature of a documented function like that?  It would be a breaking change, but also the idea of creating a differently named method to update a pivot table just for this package feels clunky, so it's probably worth it.~~

Edit: nevermind, I didn't realize that with the way the trait is used, the signature can't be altered.  We could allow for `id` to be null, however, which still feels clunky, but at least would be backward compatible.

**Comment by ankurk91** [comment]
You really no need to use `updateExistingPivot` on a one to one relation.

You can update child relation like:
```php
<?php
$restaurant = Restaurant::first();

$restaurant->operator()->update([
   'name' => 'updated name'
])
```
The above example has been taken from readme.md
