### ISSUE TITLE
Not able to be add Latest to relationship

### ISSUE THREAD

**Issue by JeffreyDavidson** [ankurk91/laravel-eloquent-relationships#2]
**I'm submitting a ...**  (check one with "x")

```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* Laravel version : 10.x
* php version : 8.2
* Database name and version : MySql

**Current behavior**
Currently, when running Larastan I get the reported error. 

  Line   Models/Concerns/CanJoinTeams.php (in context of class App\Models\Player)              
 ------ ------------------------------------------------------------------------------------------- 
  42     Call to private method latest() of parent class                                            
         Illuminate\Database\Eloquent\Relations\BelongsToMany<Illuminate\Database\Eloquent\Model>.  

**Expected behavior**
What I would hope to be able to do is be latest record here.

**Minimal reproduction of the problem with instructions**
`public function previousTeam(): BelongsToOne
    {
        return $this->belongsToOne(Team::class)
            ->wherePivotNotNull('left_at')
            ->withPivot(['joined_at', 'left_at'])
            ->latest('joined_at');
    }`

**Comment by ankurk91** [comment]
I don't care if larastan is giving you error about a method.
Larastan is not perfect.
Php is not typescript

**Comment by ankurk91** [comment]
You may want to use ` orderByPivot('joined_at');` 

Looks like you could not describe your issue well
